### ISSUE TITLE
WebView iOS

### ISSUE THREAD

**Issue by carlosagudop** [acaliaro/OpenPdf#1]
Hi, first of all I want to thank you to share your code, it was very useful, but i have a doubt about how to implement this, or if it is even posibble, in iOs. Thank you for your help and  sorry for my  poor english.

**Comment by acaliaro** [comment]
Hi @carlosagudop 

I think you should not have problem with iOS…. BTW I suggest to take a look to this that explain everything
https://blog.verslu.is/xamarin/xamarin-forms-xamarin/showing-pdf-files-xamarin-forms/

**Comment by carlosagudop** [comment]
Thanks!!
