### ISSUE TITLE
Is there a way to make this work offline with a local file

### ISSUE THREAD

**Issue by leonun96** [acaliaro/OpenPdf#2]
It seems it views the pdf file url via google drive, at least on Android. My question is, is there a way to download a pdf using xamarin essentials API, storing it in a custom folder like FileSystem.AppDataDirectory and then view this pdf when the phone/device is without internet connection? 
Any help would be appreciated good sir. Thanks!

**Comment by acaliaro** [comment]
I think this is your guide

https://blog.verslu.is/xamarin/xamarin-forms-xamarin/showing-pdf-files-xamarin-forms/

**Comment by leonun96** [comment]
> I think this is your guide
> 
> https://blog.verslu.is/xamarin/xamarin-forms-xamarin/showing-pdf-files-xamarin-forms/

Thanks a lot for answering, really, i've been posting everywhere with no replies from anybody.
The truth is that i already tried that answer, follow that tutorial and it didn't work at all, all i get from the pdf viewer is a "pdf.js v2.1.266 (build 81f5835c) message failed to fetch" answer, wich is really frustrating, because i don't know what causes it.
I also tried to directly open the pdf file with the browser passing it as a file:/// or content:// and it failed as well. I'm actually really stressed out because of this so if you have any ideas i would greatly appreciate it. Thanks again mate!

**Comment by acaliaro** [comment]
for "fetch fail" seems to be a solved issue

https://github.com/jfversluis/pdfjs/commit/33cb6d8f9daa32412eb650199aad295d47a98c7e

have you tried Gerald's code? he has answred to you. If you have problem with https://github.com/jfversluis/pdfjs ask to Gerald, he will answer to you

**Comment by leonun96** [comment]
Thanks again kind sir, as it turns out, it does gets rid of the error message in the pdfjs viewer, but it still doesn't show any files, even thought I use Directory.getfiles to read into the folder and it's pretty clear the pdf file is in there. I'll would try to reach out to him to see if he can help me. Thanks again for everything.
